// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zp5aZpfvP2EMgwQHirJFbr4MgjqEvEY',
    appId: '1:466231871448:web:6c26c1adc868fa72ed54ad',
    messagingSenderId: '466231871448',
    projectId: 'ecommerce-32415',
    authDomain: 'ecommerce-32415.firebaseapp.com',
    databaseURL:
        'https://ecommerce-32415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-32415.appspot.com',
    measurementId: 'G-744WE1F9TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWc_gu-28lmUAnIT0wpY5KCos9qxrZpdg',
    appId: '1:466231871448:android:7b08505ada090dc1ed54ad',
    messagingSenderId: '466231871448',
    projectId: 'ecommerce-32415',
    databaseURL:
        'https://ecommerce-32415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-32415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYJ0ZScaKLbpySYxRQxVYoWZRS0xFOZ8',
    appId: '1:466231871448:ios:f9c6b7ffb3cf5f39ed54ad',
    messagingSenderId: '466231871448',
    projectId: 'ecommerce-32415',
    databaseURL:
        'https://ecommerce-32415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-32415.appspot.com',
    androidClientId:
        '466231871448-0hgn57lgsdeu85b5b01vjj9v4lm83ifj.apps.googleusercontent.com',
    iosClientId:
        '466231871448-npashqffhbmrkm9qvltdt38ld4bpip78.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYJ0ZScaKLbpySYxRQxVYoWZRS0xFOZ8',
    appId: '1:466231871448:ios:f9c6b7ffb3cf5f39ed54ad',
    messagingSenderId: '466231871448',
    projectId: 'ecommerce-32415',
    databaseURL:
        'https://ecommerce-32415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-32415.appspot.com',
    androidClientId:
        '466231871448-0hgn57lgsdeu85b5b01vjj9v4lm83ifj.apps.googleusercontent.com',
    iosClientId:
        '466231871448-npashqffhbmrkm9qvltdt38ld4bpip78.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2-IFjgRiuBZZWBWWCjOLm_1xZHdRX3yM',
    appId: '1:466231871448:web:4fd63c6006f43ecaed54ad',
    messagingSenderId: '466231871448',
    projectId: 'ecommerce-32415',
    authDomain: 'ecommerce-32415.firebaseapp.com',
    databaseURL:
        'https://ecommerce-32415-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-32415.appspot.com',
    measurementId: 'G-1GREFEV2X3',
  );
}
